echo '#if !defined(OPENNURBS_INC_)' > opennurbs.h
echo '#define OPENNURBS_INC_' >> opennurbs.h

cat opennurbs_system.h >> opennurbs.h
cat opennurbs_3dm.h >> opennurbs.h
cat opennurbs_defines.h >> opennurbs.h
cat opennurbs_error.h >> opennurbs.h
cat opennurbs_memory.h >> opennurbs.h
cat opennurbs_rand.h >> opennurbs.h
cat opennurbs_crc.h >> opennurbs.h
cat opennurbs_uuid.h >> opennurbs.h
cat opennurbs_unicode.h >> opennurbs.h

#if defined(ON_CPLUSPLUS)

cat opennurbs_fsp.h >> opennurbs.h
cat opennurbs_string.h >> opennurbs.h
cat opennurbs_compress.h >> opennurbs.h
cat opennurbs_base64.h >> opennurbs.h
cat opennurbs_color.h >> opennurbs.h
cat opennurbs_linestyle.h >> opennurbs.h
cat opennurbs_point.h >> opennurbs.h
cat opennurbs_fpoint.h >> opennurbs.h
cat opennurbs_array.h >> opennurbs.h
cat opennurbs_base32.h >> opennurbs.h
cat opennurbs_pluginlist.h >> opennurbs.h
cat opennurbs_bounding_box.h >> opennurbs.h
cat opennurbs_matrix.h >> opennurbs.h
cat opennurbs_xform.h >> opennurbs.h
cat opennurbs_workspace.h >> opennurbs.h
cat opennurbs_plane.h >> opennurbs.h
cat opennurbs_circle.h >> opennurbs.h
cat opennurbs_ellipse.h >> opennurbs.h
cat opennurbs_x.h >> opennurbs.h
cat opennurbs_line.h >> opennurbs.h
cat opennurbs_polyline.h >> opennurbs.h
cat opennurbs_cylinder.h >> opennurbs.h
cat opennurbs_cone.h >> opennurbs.h
cat opennurbs_sphere.h >> opennurbs.h
cat opennurbs_box.h >> opennurbs.h
cat opennurbs_torus.h >> opennurbs.h
cat opennurbs_bezier.h >> opennurbs.h
cat opennurbs_math.h >> opennurbs.h
cat opennurbs_intersect.h >> opennurbs.h
cat opennurbs_optimize.h >> opennurbs.h
cat opennurbs_knot.h >> opennurbs.h
cat opennurbs_evaluate_nurbs.h >> opennurbs.h
cat opennurbs_textlog.h >> opennurbs.h
cat opennurbs_zlib.h >> opennurbs.h
cat opennurbs_rtree.h >> opennurbs.h
cat opennurbs_mapchan.h >> opennurbs.h
cat opennurbs_rendering.h >> opennurbs.h
cat opennurbs_archive.h >> opennurbs.h
cat opennurbs_massprop.h >> opennurbs.h
cat opennurbs_arc.h >> opennurbs.h
cat opennurbs_object.h >> opennurbs.h
cat opennurbs_userdata.h >> opennurbs.h
cat opennurbs_geometry.h >> opennurbs.h
cat opennurbs_curve.h >> opennurbs.h
cat opennurbs_surface.h >> opennurbs.h
cat opennurbs_viewport.h >> opennurbs.h
cat opennurbs_texture_mapping.h >> opennurbs.h
cat opennurbs_texture.h >> opennurbs.h
cat opennurbs_material.h >> opennurbs.h
cat opennurbs_layer.h >> opennurbs.h
cat opennurbs_linetype.h >> opennurbs.h
cat opennurbs_group.h >> opennurbs.h
cat opennurbs_font.h >> opennurbs.h
cat opennurbs_light.h >> opennurbs.h
cat opennurbs_pointgeometry.h >> opennurbs.h
cat opennurbs_pointcloud.h >> opennurbs.h
cat opennurbs_curveproxy.h >> opennurbs.h
cat opennurbs_surfaceproxy.h >> opennurbs.h
cat opennurbs_mesh.h >> opennurbs.h
cat opennurbs_pointgrid.h >> opennurbs.h
cat opennurbs_linecurve.h >> opennurbs.h
cat opennurbs_arccurve.h >> opennurbs.h
cat opennurbs_polylinecurve.h >> opennurbs.h
cat opennurbs_nurbscurve.h >> opennurbs.h
cat opennurbs_polycurve.h >> opennurbs.h
cat opennurbs_curveonsurface.h >> opennurbs.h
cat opennurbs_nurbssurface.h >> opennurbs.h
cat opennurbs_planesurface.h >> opennurbs.h
cat opennurbs_revsurface.h >> opennurbs.h
cat opennurbs_sumsurface.h >> opennurbs.h
cat opennurbs_brep.h >> opennurbs.h
cat opennurbs_beam.h >> opennurbs.h
cat opennurbs_bitmap.h >> opennurbs.h
cat opennurbs_instance.h >> opennurbs.h
cat opennurbs_3dm_properties.h >> opennurbs.h
cat opennurbs_3dm_settings.h >> opennurbs.h
cat opennurbs_3dm_attributes.h >> opennurbs.h
cat opennurbs_annotation.h >> opennurbs.h
cat opennurbs_annotation2.h >> opennurbs.h
cat opennurbs_hatch.h >> opennurbs.h
cat opennurbs_dimstyle.h >> opennurbs.h
cat opennurbs_hatch.h >> opennurbs.h
cat opennurbs_linetype.h >> opennurbs.h
cat opennurbs_objref.h >> opennurbs.h
cat opennurbs_offsetsurface.h >> opennurbs.h
cat opennurbs_detail.h >> opennurbs.h
cat opennurbs_lookup.h >> opennurbs.h
cat opennurbs_object_history.h >> opennurbs.h
cat opennurbs_extensions.h >> opennurbs.h

echo '#endif' >> opennurbs.h
#echo '#endif' >> opennurbs.h

